server:
  port: ${SERVER_PORT:8083}

spring:
  application:
    name: subscription-service

  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5435/subscription_service}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:admin}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yml

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9094}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://localhost:8761/eureka/}
    register-with-eureka: ${EUREKA_REGISTER_WITH_EUREKA:true}
    fetch-registry: ${EUREKA_FETCH_REGISTRY:false}
  instance:
    prefer-ip-address: ${EUREKA_PREFER_IP_ADDRESS:true}
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}

app:
  kafka:
    subscription-events-topic: ${KAFKA_SUBSCRIPTION_EVENTS_TOPIC:subscription-events}

  subscriptions:
    expiration-check-fixed-delay-ms: ${SUBSCRIPTION_EXPIRATION_CHECK_FIXED_DELAY_MS:60000}
    expiration-lock-at-most-for: ${SUBSCRIPTION_EXPIRATION_LOCK_AT_MOST_FOR:PT5M}
    expiration-lock-at-least-for: ${SUBSCRIPTION_EXPIRATION_LOCK_AT_LEAST_FOR:PT5S}
